/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorsRouteImport } from './routes/tutors'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CurriculumsRouteImport } from './routes/curriculums'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingConfirmedRouteImport } from './routes/booking-confirmed'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const TutorsRoute = TutorsRouteImport.update({
  id: '/tutors',
  path: '/tutors',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumsRoute = CurriculumsRouteImport.update({
  id: '/curriculums',
  path: '/curriculums',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmedRoute = BookingConfirmedRouteImport.update({
  id: '/booking-confirmed',
  path: '/booking-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/curriculums': typeof CurriculumsRoute
  '/faq': typeof FaqRoute
  '/payments': typeof PaymentsRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tutors': typeof TutorsRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/curriculums': typeof CurriculumsRoute
  '/faq': typeof FaqRoute
  '/payments': typeof PaymentsRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tutors': typeof TutorsRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/curriculums': typeof CurriculumsRoute
  '/faq': typeof FaqRoute
  '/payments': typeof PaymentsRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tutors': typeof TutorsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/booking-confirmed'
    | '/contact'
    | '/courses'
    | '/curriculums'
    | '/faq'
    | '/payments'
    | '/schedule'
    | '/sitemap.xml'
    | '/tutors'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/booking-confirmed'
    | '/contact'
    | '/courses'
    | '/curriculums'
    | '/faq'
    | '/payments'
    | '/schedule'
    | '/sitemap.xml'
    | '/tutors'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/booking-confirmed'
    | '/contact'
    | '/courses'
    | '/curriculums'
    | '/faq'
    | '/payments'
    | '/schedule'
    | '/sitemap.xml'
    | '/tutors'
    | '/_authenticated/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookingConfirmedRoute: typeof BookingConfirmedRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  CurriculumsRoute: typeof CurriculumsRoute
  FaqRoute: typeof FaqRoute
  PaymentsRoute: typeof PaymentsRoute
  ScheduleRoute: typeof ScheduleRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TutorsRoute: typeof TutorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutors': {
      id: '/tutors'
      path: '/tutors'
      fullPath: '/tutors'
      preLoaderRoute: typeof TutorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculums': {
      id: '/curriculums'
      path: '/curriculums'
      fullPath: '/curriculums'
      preLoaderRoute: typeof CurriculumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirmed': {
      id: '/booking-confirmed'
      path: '/booking-confirmed'
      fullPath: '/booking-confirmed'
      preLoaderRoute: typeof BookingConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookingConfirmedRoute: BookingConfirmedRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  CurriculumsRoute: CurriculumsRoute,
  FaqRoute: FaqRoute,
  PaymentsRoute: PaymentsRoute,
  ScheduleRoute: ScheduleRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TutorsRoute: TutorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
